### ISSUE TITLE
AxGraves integration

### ISSUE THREAD

**Issue by s-droid-jh** [playgamesgo/InventoryDropChance#5]
Hi! I really like your resource!

However, the plugin doesn’t work with AxGraves version 1.31.0. Would it be possible to update the AxGraves integration?

It seems that InventoryDropChance 1.9.0 was compiled against an older AxGraves API, while AxGraves 1.31.0 has changed its internal API.

Here is the error from the console:

```
[18:00:48 ERROR]: Could not pass event PlayerDeathEvent to InventoryDropChance v1.9.0
java.lang.NoSuchMethodError: 'void com.artillexstudios.axgraves.grave.Grave.<init>(org.bukkit.Location, org.bukkit.OfflinePlayer, java.util.List, int, long)'
        at InventoryDropChance-1.9.0-all.jar//me.playgamesgo.inventorydropchance.utils.AxGravesIntegration.summonGrave(AxGravesIntegration.java:46) ~[?:?]
        at InventoryDropChance-1.9.0-all.jar//me.playgamesgo.inventorydropchance.listeners.PlayerDeathListener.onPlayerDeath(PlayerDeathListener.java:149) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:71) ~[purpur-api-26.2.build.2620-stable.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-26.2.jar:26.2-2620-8762b2f]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-26.2.jar:26.2-2620-8762b2f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[purpur-26.2.jar:26.2-2620-8762b2f]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:1021) ~[purpur-26.2.jar:26.2-2620-8762b2f]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:1180) ~[purpur-26.2.jar:26.2-2620-8762b2f]
        at org.bukkit.craftbukkit.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:145) ~[purpur-26.2.jar:26.2-2620-8762b2f]
        at CMI-9.8.9.8.jar//com.Zrips.CMI.commands.list.kill.lambda$0(kill.java:112) ~[?:?]
        at CMILib1.5.9.9.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runAtEntity$3(CMILib.java:158) ~[?:?]
```

Server: Purpur 26.2

Thank you for your work on this resource!

**Comment by playgamesgo** [comment]
Hi, thanks for the report, I fixed it and I will publish update to modrinth and spigot soon
